server:
  port: 7000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: eureka-provider