eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 4440
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaoxinlei/springcloud-demo/   # 配置git仓库的地址
          search-paths: config # git仓库地址下的相对地址，可以配置多个，用,分割。
          #username: # git仓库的账号
          #password: # git仓库的密码